import hashlib
from sqlalchemy import select
from sqlalchemy.orm import Session
from passlib.context import CryptContext

from bkend import models
from bkend.schemas import ArticleCreate
from bkend.crud import create_user, get_user_by_email, create_article, get_articles_with_votes



PWD_CONTEXT = CryptContext(schemes=["pbkdf2_sha256"], deprecated="auto")


def get_password_hash(password: str) -> str:
    """Match the application's pre-hash + CryptContext logic.

    We compute SHA-256 hex digest then hash that with the configured
    CryptContext so produced hashes match those generated by the app.
    """
    if isinstance(password, str):
        pw_bytes = password.encode("utf-8")
    else:
        pw_bytes = password
    sha_hex = hashlib.sha256(pw_bytes).hexdigest()
    return PWD_CONTEXT.hash(sha_hex)


def main() -> None:
    """Populate the database with an admin user, if one does not already exist,
    or promote the existing user to admin..

    Run from the project root:  python -m bkend.scripts.populate_db
    """
    models.init_db()
    email = "admin@ex.com"
    raw_password = "pass"

    with Session(models.engine) as db:
        user = get_user_by_email(db, email=email)
        if user:
            if getattr(user, "is_admin", False):
                print(f"User {email} already exists and is an admin")
                articles = get_articles_with_votes(db, user.id)
                print("Articles in db: ", articles)
                return
            user.is_admin = True
            db.commit()
            print(f"Existing user {email} promoted to admin")
            return

        hashed = get_password_hash(raw_password)
        create_user(db, email=email, hashed_password=hashed)
        # Ensure the created user is marked admin
        created = get_user_by_email(db, email=email)
        if created:
            created.is_admin = True
            db.commit()
            print(f"Created admin user {email} with password '{raw_password}'")
        else:
            print("Failed to create admin user")

        # Create two test articles authored by the admin if they don't exist
        admin_user = created
        if admin_user:
            existing_articles = db.execute(select(models.Article)).scalars().all()
            if not existing_articles:
                print("Adding two test articles...")
                art_data = ArticleCreate(
                    title="Welcome to Dikipedia",
                    content="This is the first test article.",
                    image_url="./media/cfclasspic.png"
                )
                create_article(db, art_data, author_id=admin_user.id)

                art_data = ArticleCreate(
                    title="Second Article",
                    content="Another satirical piece for testing.",
                    image_url="./media/cfclasspic.png"
                )
                create_article(db, art_data, author_id=admin_user.id)
                print("Added test articles; sample: ", art_data)
            else:
                print("Articles already present; skipping test article creation")


# Helper function to update the image_url of an article by its id
def update_article_image_url(db: Session, article_id: int, new_image_url: str) -> None:
    article = db.get(models.Article, article_id)
    if article:
        article.image_url = new_image_url
        db.commit()


# Function to update image URLs of existing articles; takes a list of tuples (id, new_url)
def update_existing_articles_images(articles: list[tuple[int, str]]) -> None:
    models.init_db()
    with Session(models.engine) as db:
        for article_id, new_url in articles:
            update_article_image_url(db, article_id, new_url)
            print(f"Updated article id {article_id} image_url to {new_url}")


if __name__ == "__main__":
    main()

    articles_to_update = [
        (1, "./media/planetower.webp"),
        (2, "./media/crypto-moguls.webp"),
        (3, "./media/milei.jpeg"),
        (4, "./media/trump-zelensky.webp"),
    ]
    update_existing_articles_images(articles_to_update)